# Generated by Django 5.0 on 2025-11-06 23:28

import stationery.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationery', '0007_alter_items_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='display_image',
            field=models.ImageField(blank=True, null=True, upload_to=stationery.utils.upload_display_image),
        ),
    ]
