# Generated by Django 5.0 on 2025-11-06 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationery', '0008_alter_items_display_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastprintouts',
            name='print_on_one_side',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activeprintouts',
            name='print_on_one_side',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
