# Generated by Django 5.0 on 2025-11-07 00:05

import django.db.models.deletion
import stationery.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationery', '0009_pastprintouts_print_on_one_side_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintoutFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=stationery.utils.printout_file_rename)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_size', models.BigIntegerField(default=0)),
                ('printout_active', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='stationery.activeprintouts')),
                ('printout_past', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='stationery.pastprintouts')),
            ],
            options={
                'verbose_name_plural': 'Printout Files',
                'db_table': 'stationery_printout_files',
            },
        ),
    ]
