# Generated by Django 5.0 on 2025-11-07 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationery', '0010_printoutfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='printoutfile',
            name='black_and_white_pages',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='printoutfile',
            name='coloured_pages',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='printoutfile',
            name='print_on_one_side',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
