# Generated by Django 5.0 on 2025-11-07 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stationery', '0011_printoutfile_black_and_white_pages_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activeprintouts',
            name='black_and_white_pages',
        ),
        migrations.RemoveField(
            model_name='activeprintouts',
            name='coloured_pages',
        ),
        migrations.RemoveField(
            model_name='activeprintouts',
            name='print_on_one_side',
        ),
        migrations.RemoveField(
            model_name='pastprintouts',
            name='black_and_white_pages',
        ),
        migrations.RemoveField(
            model_name='pastprintouts',
            name='coloured_pages',
        ),
        migrations.RemoveField(
            model_name='pastprintouts',
            name='print_on_one_side',
        ),
    ]
